apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssqldb
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest 
          ports:
            - containerPort: 1433  # Exposes container port
          envFrom:
            - configMapRef:
                name: mssql-config
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-pv-claim