apiVersion: v1
kind: Service
metadata:
  name: gooleopenid-service
spec:
  type: LoadBalancer
  selector:
    app: gooleopenid
  ports:
  - name: gooleopenid
    protocol: TCP
    port: 80
    targetPort: 80